laravel/routes/web.php
<?php

/*use App\Historial_producto;
use App\Historial_animale;
use App\Cliente;*/

//Pagina principal de la web
/*Route::get('/', function () {
    return view('index');
});*/

Route::get('/','PrincipalController@index');

Route::get('/home', 'HomeController@index')->name('home');

//Rutas para registro/logeo... usuarios
Auth::routes();

//Para que el administrador Agrege/modifique/borre usuarios usa el middleware para que solo puedan entrar administradores
Route::resource("/admin/users","AdminUsersController")->middleware('EsAdmin');

//Para que los usuarios puedan ver/modificar su Perfil
Route::resource("/perfil","DatosController")->middleware('auth');

//Para que los usuarios puedan ver/crear y eliminar articulos para trueque
Route::resource("/trueque","ArticulotruequesController")->middleware('auth');

//Para que los usuarios puedan ver/crear y eliminar articulos para vender
Route::resource("/venta","ArticuloventasController")->middleware('auth');

//Para que el moderador publique articulos de trueque
Route::resource("/moder/true","ModerPubliController")->middleware('EsMod');
//Para que el moderador publique articulos de venta
Route::resource("/moder/vent","ModerPubliVenController")->middleware('EsMod');

//Para que todos vean los Articulos de trueque
Route::resource("/publitrue","PublitrueController");
//Para que todos vean los Articulos para Comprar
Route::resource("/publivent","PubliventController");

//Para que los usuarios puedan comprar articulos
Route::resource("/compra","ComprasController")->middleware('auth');

//Para que los usuarios puedan ofrecer articulos para cambiarlos
Route::resource("/cambio","CambioController")->middleware('auth');



//Para redireccion con la lista de rutas propia de laravel

/*Route::resource("/animales","AnimalesController")->middleware('auth');

Route::resource("/productos","ProductosController")->middleware('auth');

Route::resource("/clientes","ClientesController")->middleware('auth');

Route::resource("/historial_productos","Historial_ProductoController")->middleware('auth')->middleware('EsAdmin');

Route::get('/comprado', function () {
    return view('historial_productos.comprado');
})->middleware('auth')->middleware('EsAdmin');

Route::get('/nocomprado', function () {
    return view('historial_productos.nocomprado');
})->middleware('auth')->middleware('EsAdmin');

Route::resource("/historial_animales","Historial_AnimaleController")->middleware('auth')->middleware('EsAdmin');

Route::get('/compradoa', function () {
    return view('historial_animales.comprado');
})->middleware('auth')->middleware('EsAdmin');

Route::get('/nocompradoa', function () {
    return view('historial_animales.nocomprado');
})->middleware('auth')->middleware('EsAdmin');


*/
//para usuarios no registrados
//->middleware('auth');
//->middleware('EsUser');
//->middleware('EsAdmin');




/*Route::post('/buscar','BusquedaController@buscar');*/

//PRUEBA DE SUBCONSULTAS
/*Route::get('/lorem', function () {
  //  $comments = App\Producto::find(1)->comments;

    $comments = App\Cliente::where("Nombre","Chaim")->first()->comments;

    foreach ($cliente as $key){
      echo $key->Precio;
      echo $key->stock;
      echo $key->cliente_id;
      echo $key->producto_id;
    }

});*/

/*Route::get("animales","AnimalesController@index");

Route::post("animales","AnimalesController@store");

Route::get("animales/create","AnimalesController@create");

Route::put("animales/{animale}","AnimalesController@update");

Route::delete("animales/{animale}","AnimalesController@destroy");

Route::get("animales/{animale}/edit","AnimalesController@edit");*/

//Paginas de animales
/*Route::get("crearanimales","AnimalesController@create");
Route::get("leeranimales","AnimalesController@index");*/

/*
Route::get('/lorem', function () {
    return ('lo que tu quieras que salga');
});

Route::get('usuario','ControllerUsuario@index');
Route::get('saboteador','ControllerUsuario@sabotearUsuario');

//rutas ej migracion
Route::get('ruta66','ControllerAlumno@ruta66');

Route::get('area51','ControllerProfesor@random');

Route::get('/palabra', function () {
    return ('lo que tu quieras que salga');

//Ejercicio 21 ene 2020

Route::resource('products2','Product2Controller');

});*/

laravel/app/Http/Controllers/PublitrueController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Articulotrueque;

class PublitrueController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $trueque=Articulotrueque::all();

        return view("publitrue.index", compact("trueque"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // ver el articulo seleccionado

        $trueque=Articulotrueque::findOrFail($id);

        return view("publitrue.edit", compact("trueque"));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

laravel/resources/views/publitrue/edit.blade.php
@extends('layouts.plantilla')

@section('menu')

@endsection

@section('titulo')

Articulo Trueque

@endsection

@section('contenido')


<style type="text/css">

.zoom {
-webkit-transition: all 0.35s ease-in-out;
-moz-transition: all 0.35s ease-in-out;
transition: all 0.35s ease-in-out;
cursor: -webkit-zoom-in;
cursor: -moz-zoom-in;
cursor: zoom-in;
}

.zoom:hover,
.zoom:active,
.zoom:focus {
-ms-transform: scale(2);
-moz-transform: scale(2);
-webkit-transform: scale(2);
-o-transform: scale(2);
transform: scale(2);
position:relative;
z-index:100;
}

.DivName {cursor: pointer}
}

</style>

<div class="container mt-5">
  <div class="row">
    <div class="col-6">
      <img class="d-block img-thumbnail zoom DivName" max-width: "100%" height="auto" src="../../img/{{$trueque->img}}"/>
      <h5>{{$trueque->descripcion}}</h5>
    </div>
    <div class="col-6">
      <div class="">
        <h3>{{$trueque->nombre}}</h3>
      </div>
      <div class="mt-4">
        <h4>Articulos Buscados </h4>
        <p>{{$trueque->artbuscados}}</p>
      </div>
      <div class="mt-4">
        <h4 class="d-inline">Condición: </h4><p class="d-inline"> {{$trueque->condicion}}</p>
      </div>
      <div class="mt-4">
        <h4 class="d-inline">Época: </h4><p class="d-inline">{{$trueque->epoca}}</p>
      </div>
      <div class="mt-4">
        <h4 class="d-inline">Año: </h4><p class="d-inline">{{$trueque->agno}}</p>
      </div>
      <div class="mt-4">
        <h4 class="d-inline">Nacionalidad: </h4><p class="d-inline">{{$trueque->nacionalidad}}</p>
      </div>
      <div class="mt-4">
        <h4 class="d-inline">Tipo de Articulo: </h4><p class="d-inline">{{$trueque->tipo}}</p>
      </div>
      <div class="mt-4">
        <a href="{{route('cambio.edit',$trueque->id)}}" class="btn btn-primary btn-lg" role="button">Ofrecer Cambio</a>
      </div>
    </div>
  </div>

@endsection

laravel/resources/views/publitrue/index.blade.php
@extends('layouts.plantilla')

@section('menu')

@endsection

@section('titulo')

Articulos Trueque

@endsection

@section('contenido')

@if (isset($trueque))
@foreach ($trueque->chunk(3) as $trueq)
<div class="row">
  @foreach($trueq as $tru)
  @if ($tru->flag==1)
  <div class="col-md-4">
    <div class="card border-primary mb-3 mx-auto" style="max-width: 20rem;">
      <div class="card-header"><h3 class="text-center">{{$tru->nombre}}</h3></div>
      <div class="card-body">
        <div class="thumbnail">
          <img class="mx-auto d-block img-thumbnail" width="242px" height="auto" src="img/{{$tru->img}}"/>
          <div class="caption">
            <h3 class="text-center">Descripción</h3>
            <p>{{$tru->descripcion}}</p>
            <h3 class="text-center">Busco a Cambio</h3>
            <p>{{$tru->artbuscados}}</p>
            <p><a href="{{route('publitrue.edit',$tru->id)}}" class="btn btn-primary" role="button">Ver Mas</a> <a href="{{route('cambio.edit',$tru->id)}}" class="btn btn-outline-success" role="button">Ofrecer Cambio</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  @endif
  @endforeach
</div>
@endforeach
@endif

@endsection